/*target = args[0];

function commas(x) {
  return x.toLocaleString();
}

while (true) {
    if (getServerMoneyAvailable !== 0) {
        //weaken(target);
        preHackMoney = getServerMoneyAvailable(target);
        tprint('////////////////////////////');
        tprint('Hacking ' + target + '.');
        hack(target);
        postHackMoney = getServerMoneyAvailable(target);
        takeAway = (preHackMoney - postHackMoney);
        tprint('You stole $' + commas(takeAway) + '. Nice.');
        tprint('There is currently $' + commas((getServerMoneyAvailable(target))) + ' available.');
    } else {
        tprint('/////////////////////////////////////');
        tprint('No more money on ' + target + '!');
    }
}

tprint('///////////');
tprint('---DONE!---');
tprint('///////////');
*/


basicServers = ['sigma-cosmetics'];
scriptRam = 1.50;
totalRam = ((getServerRam('home')[0]) - (getServerRam('home')[1]));
maxThreads = (Math.floor(totalRam / scriptRam));


function commas(x) {
  return x.toLocaleString();
}

for (i = 0; i < basicServers.length; i = i + 1) {
    target = basicServers[i];
    
    while (getServerMoneyAvailable(target) > 75000) {
        //weaken(target);
        preHackMoney = getServerMoneyAvailable(target);
        tprint('///////////////////////////////////////////////');
        tprint('Hacking ' + target + '...');
        exec('RemoteHack.script', 'home', maxThreads, target);
        while ((scriptRunning('RemoteHack.script', 'home')) === true) {
            sleep(3000);
        }
        postHackMoney = getServerMoneyAvailable(target);
        takeAway = (preHackMoney - postHackMoney);
        tprint('You stole $' + commas(takeAway) + '. Nice.');
        tprint('There is currently $' + commas((getServerMoneyAvailable(target))) + ' available.');
    } 
    
    tprint('///////////////////////////////////////////////');
    tprint('Not enough money on ' + target + ' to care!');
}

tprint('///////////');
tprint('---DONE!---');
tprint('///////////');